apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dmi-test
  region: us-west-2

nodeGroups:
  - name: dmi-ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    labels:
      nodegroup-type: ingress-controller
