apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport-service
  namespace: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30002
  type: NodePort
