apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: prometheus
spec:
  selector:
    app.kubernetes.io/component: server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
